import io
import time
from datetime import datetime
import numpy as np
from PIL import Image
import streamlit as st
import tensorflow as tf

# Optional Serial Import for Arduino Telemetry
try:
    import serial
    SERIAL_AVAILABLE = True
except ImportError:
    SERIAL_AVAILABLE = False

# ReportLab Imports for PDF Generation
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

# ==========================================
# 1. PAGE CONFIGURATION & STYLING
# ==========================================
st.set_page_config(
    page_title="Cellular Vision — Edge AI Botanical Explorer",
    page_icon="🍃",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS styling
st.markdown("""
<style>
    .main-header { font-size: 2.2rem; color: #1b4332; font-weight: bold; text-align: center; margin-bottom: 0px; }
    .sub-header { font-size: 1.1rem; color: #2a9d8f; text-align: center; margin-bottom: 20px; }
    .metric-card { background-color: #f8f9fa; border-radius: 10px; padding: 15px; border-left: 5px solid #2a9d8f; margin-bottom: 10px; }
</style>
""", unsafe_allow_html=True)

# ==========================================
# 2. HARDWARE & MODEL SETUP
# ==========================================
labels = [
    "Apple - Apple Scab", "Apple - Black Rot", "Apple - Cedar Apple Rust", "Apple - Healthy",
    "Corn - Cercospora Leaf Spot", "Corn - Common Rust", "Corn - Northern Leaf Blight", "Corn - Healthy",
    "Potato - Early Blight", "Potato - Late Blight", "Potato - Healthy",
    "Tomato - Bacterial Spot", "Tomato - Early Blight", "Tomato - Late Blight", "Tomato - Healthy"
]

@st.cache_resource
def load_tflite_model():
    interpreter = tf.lite.Interpreter(model_path="model.tflite")
    interpreter.allocate_tensors()
    return interpreter

try:
    interpreter = load_tflite_model()
    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()
    model_loaded = True
except Exception as e:
    model_loaded = False
    st.error(f"Error loading model.tflite: {e}")

def send_serial_command(command, port="COM3", baudrate=9600):
    if not SERIAL_AVAILABLE:
        return "Serial library not installed."
    try:
        ser = serial.Serial(port, baudrate, timeout=1)
        time.sleep(1.5)
        ser.write(command.encode())
        ser.close()
        return f"Signal '{command}' sent to {port}."
    except Exception as e:
        return f"Hardware offline: {e}"

# ==========================================
# 3. REPORT GENERATOR FUNCTIONS
# ==========================================
def generate_text_report(disease_name, confidence, status_type, pH_range, remedies):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_text = f"""
====================================================================
               CELLULAR VISION - DIAGNOSTIC REPORT                  
====================================================================
Timestamp          : {timestamp}
Diagnosis          : {disease_name}
Model Confidence   : {confidence:.2f}%
Status Severity    : {status_type.upper()}

--------------------------------------------------------------------
1. AGRONOMIC & SOIL PROFILE
--------------------------------------------------------------------
Optimal Soil pH    : {pH_range}
Status Indicator   : {status_type} (Hardware Telemetry Triggered)

--------------------------------------------------------------------
2. ACTIONABLE TREATMENT & REMEDIATION PROTOCOL
--------------------------------------------------------------------
{remedies}

--------------------------------------------------------------------
Generated by Cellular Vision Edge AI Platform
Zero Cloud Latency • Offline Edge Inference • IoT Hardware Telemetry
====================================================================
"""
    return report_text.strip()


def generate_pdf_report(disease_name, confidence, status_type, pH_range, remedies):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )
    
    story = []
    styles = getSampleStyleSheet()

    NAVY = colors.HexColor("#0d1f2d")
    GREEN = colors.HexColor("#1b4332")
    TEAL = colors.HexColor("#2a9d8f")
    DARK_TEXT = colors.HexColor("#2b2d42")

    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        textColor=NAVY,
        spaceAfter=4
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=10,
        textColor=TEAL,
        spaceAfter=15
    )

    story.append(Paragraph("🍃 Cellular Vision — Diagnostic Summary", title_style))
    story.append(Paragraph("AI-Powered Botanical Explorer & Edge Hardware Telemetry Report", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=2, color=GREEN, spaceAfter=15))

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    table_data = [
        [Paragraph("<b>Parameter</b>", styles['Normal']), Paragraph("<b>Value / Assessment</b>", styles['Normal'])],
        ["Generated Timestamp", timestamp],
        ["Identified Condition", disease_name],
        ["Model Confidence Score", f"{confidence:.2f}%"],
        ["Health Classification", status_type.capitalize()],
        ["Recommended Soil pH Target", pH_range]
    ]

    t = Table(table_data, colWidths=[180, 350])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), colors.HexColor("#f1faee")),
        ('TEXTCOLOR', (0, 0), (-1, -1), DARK_TEXT),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e0e0e0")),
    ]))
    story.append(t)
    story.append(Spacer(1, 15))

    sec_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=13,
        textColor=NAVY,
        spaceAfter=6
    )
    body_style = ParagraphStyle(
        'BodyText',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        textColor=DARK_TEXT,
        leading=14
    )

    story.append(Paragraph("Actionable Remediation Protocol", sec_style))
    story.append(HRFlowable(width="100%", thickness=1, color=TEAL, spaceAfter=10))
    story.append(Paragraph(remedies.replace("\n", "<br/>"), body_style))
    story.append(Spacer(1, 20))

    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=8,
        textColor=colors.HexColor("#8d99ae"),
        alignment=1
    )
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.lightgrey, spaceAfter=10))
    story.append(Paragraph("Cellular Vision Edge AI Platform • Confidential Agronomic Diagnostic Export", footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer

# ==========================================
# 4. STREAMLIT USER INTERFACE
# ==========================================
st.markdown('<div class="main-header">Cellular Vision — Edge AI Platform</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">Real-Time Foliar Diagnostics & Embedded Telemetry</div>', unsafe_allow_html=True)

# Sidebar Configuration
st.sidebar.title("🛠️ Hardware & Settings")
com_port = st.sidebar.text_input("Arduino COM Port", value="COM3")
enable_hardware = st.sidebar.checkbox("Enable Serial Hardware", value=False)

# File Input Mode
input_mode = st.radio("Select Input Method:", ["📁 Upload Foliar Image", "📸 Live Camera"])

uploaded_file = None
if input_mode == "📁 Upload Foliar Image":
    uploaded_file = st.file_uploader("Choose a leaf image sample...", type=["jpg", "jpeg", "png"])
else:
    uploaded_file = st.camera_input("Snap a live photo of a leaf")

if uploaded_file is not None and model_loaded:
    image = Image.open(uploaded_file).convert("RGB")
    
    col_img, col_res = st.columns([1, 1])
    
    with col_img:
        st.image(image, caption="Uploaded Foliar Sample", use_container_width=True)

    # Image Preprocessing
    img_resized = image.resize((224, 224))
    input_data = np.expand_dims(np.array(img_resized, dtype=np.float32) / 255.0, axis=0)

    # Perform TFLite Inference
    interpreter.set_tensor(input_details[0]['index'], input_data)
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details[0]['index'])[0]

    # Process Predictions
    pred_idx = np.argmax(output_data)
    confidence_score = float(output_data[pred_idx] * 100) if max(output_data) <= 1.0 else float(output_data[pred_idx])
    raw_label = labels[pred_idx] if pred_idx < len(labels) else "Unknown Condition"

    # Severity Mapping & Hardware Control
    if "Healthy" in raw_label:
        status_type = "Healthy"
        signal = "H"
        ph_range = "6.0 - 7.0"
        status_color = "green"
        remedies = "1. Plant physiological status is nominal.\n2. Maintain regular irrigation schedule.\n3. Continue monitoring soil electrical conductivity (EC)."
    elif "Blight" in raw_label or "Rust" in raw_label or "Spot" in raw_label:
        status_type = "Infected (Biotic Stress)"
        signal = "I"
        ph_range = "5.8 - 6.5"
        status_color = "red"
        remedies = "1. Isolate affected foliage immediately to limit spore dispersion.\n2. Apply organic bio-fungicide or copper hydroxide spray.\n3. Transition to drip irrigation to keep leaf canopy dry."
    else:
        status_type = "Deficient (Abiotic Stress)"
        signal = "D"
        ph_range = "6.2 - 6.8"
        status_color = "orange"
        remedies = "1. Perform macronutrient soil analysis (N, P, K, Fe).\n2. Supplement with foliar organic chelated iron or compost tea.\n3. Buffer soil pH to optimal zone for root absorption."

    if enable_hardware:
        hw_status = send_serial_command(signal, port=com_port)
        st.sidebar.info(hw_status)

    # Display Results in original Card Layout
    with col_res:
        st.markdown(f"### Diagnostic Result")
        st.markdown(f"**Identified Condition:** `{raw_label}`")
        st.progress(min(int(confidence_score), 100))
        st.markdown(f"**Confidence:** `{confidence_score:.2f}%`")
        
        st.markdown(f"""
        <div class="metric-card">
            <h4>Health Classification</h4>
            <p style="color:{status_color}; font-size:1.2rem; font-weight:bold; margin:0;">{status_type}</p>
        </div>
        <div class="metric-card">
            <h4>Recommended Soil pH Target</h4>
            <p style="font-size:1.1rem; font-weight:bold; margin:0;">{ph_range}</p>
        </div>
        """, unsafe_allow_html=True)

        st.markdown("---")
        st.markdown("**Actionable Remediation Protocol:**")
        st.text(remedies)

    # ==========================================
    # 5. ONE-CLICK PDF & TEXT REPORT EXPORT
    # ==========================================
    st.markdown("---")
    st.subheader("📄 Export Diagnostic Summary Report")

    text_report = generate_text_report(raw_label, confidence_score, status_type, ph_range, remedies)
    pdf_buffer = generate_pdf_report(raw_label, confidence_score, status_type, ph_range, remedies)

    col_pdf, col_txt = st.columns(2)

    with col_pdf:
        st.download_button(
            label="📥 Download PDF Report (.pdf)",
            data=pdf_buffer,
            file_name=f"CellularVision_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf",
            mime="application/pdf",
            use_container_width=True
        )

    with col_txt:
        st.download_button(
            label="📝 Download Text Report (.txt)",
            data=text_report,
            file_name=f"CellularVision_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.txt",
            mime="text/plain",
            use_container_width=True
        )
